project:
  type: website
  output-dir: docs


language: 
  search-box-placeholder: Search

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1rem

website:
  back-to-top-navigation: true
  search:
    location: navbar
    type: textbox

  title: "tidymodeling"
  favicon: "logo.jpg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: recipe.qmd
        text: Recipe
      - about.qmd
      - sidebar:Classification_hotel
      - sidebar:Classification_titanic
      - sidebar:house_price_regression_model
 
  page-footer:
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/)."
      
  sidebar:
    - id: Classification_hotel
      title: "hotel Classification model"
      style: "floating"
      background: light
      collapse-level: 2
      contents: hote classification model
      
    - id: Classification_titanic
      title: "titanic Classification model"
      style: "floating"
      background: light
      collapse-level: 2
      contents: titanic classification model      

    - id: house_price_regression_model
      title: "house price regression model"
      style: "floating"
      background: light
      collapse-level: 2
      contents: house price regression model 



execute:
  freeze: auto

