project:
  type: website
  output-dir: docs


language: 
  search-box-placeholder: Search



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1rem

website:
  back-to-top-navigation: true
  reader-mode: true
  search:
    location: navbar
    type: textbox

  title: "Tidymodel with R"
  image: "logo.jpg"
  favicon: "logo.jpg"
  twitter-card: true
  site-url: https://example.com
  navbar:
    left:
      - sidebar:index

     
      - sidebar:Classification_hotel
      - sidebar:Classification_titanic
      - sidebar:house_price_regression_model
      - sidebar:house_price_tensorflow
 
  page-footer:
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/)."
      
  sidebar:
    - id: index
      title: "index"
      style: "floating"
      background: light
      collapse-level: 2
      contents: index





    - id: Classification_hotel
      title: "hotel Classification model"
      style: "floating"
      background: light
      collapse-level: 2
      contents: hotel classification model
      
    - id: Classification_titanic
      title: "titanic Classification model"
      style: "floating"
      background: light
      collapse-level: 2
      contents: titanic classification model      

    - id: house_price_regression_model
      title: "house price regression model"
      style: "floating"
      background: light
      collapse-level: 2
      contents: house price regression model 

    - id: house_price_tensorflow
      title: "house price tensorflow model"
      style: "floating"
      background: light
      collapse-level: 2
      contents: tensorflow



execute:
  freeze: auto

