---
title: "K mean Clustering with image"
subtitle: "with image data"
execute:
  warning: false
  error: false
format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
---

Using K mean Clustering to replace colow on below picture


# load package

```{r}
set.seed(55)
library(tidyverse)
library(broom)
library(janitor)
library(magick)
```

# input image
```{r}
image <- image_read('images/python logo.jpg')
```


# convert png to matrix
```{r}
image_tiff <- image_convert(image, "tiff")
image_array <- as.integer(image_tiff[[1]])                
```


```{r}
magick::image_read(image_array/ 255)
```

```{r}
dim(image_array)
```

```{r}
class(image_array)
```


```{r}
image_array_old=image_array
```

# reshape from 3 D to 2 D
```{r}
dim(image_array) <- c(dim(image_array)[1]*dim(image_array)[2],3)
```

```{r}
dim(image_array)
```

# Optimal number of k-clusters


```{r}
kclusts <- 
  tibble(k = 1:9) %>%
  mutate(
    kclust = map(k, ~kmeans(image_array, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, image_array)
  )

kclusts
```


```{r}
clusters <- 
  kclusts %>%
  unnest(cols = c(tidied))

assignments <- 
  kclusts %>% 
  unnest(cols = c(augmented))

clusterings <- 
  kclusts %>%
  unnest(cols = c(glanced))
```



```{r}
library(scales)
ggplot(clusterings, aes(k, tot.withinss)) +
  geom_line() +
  geom_point()+scale_x_continuous(breaks= pretty_breaks())
```



# group to 3 

```{r}
kclust <- kmeans(image_array, centers = 3)
```

```{r}
result=augment(kclust, image_array) %>% clean_names()
```



```{r}
result %>% count(cluster)
```

# change  2 color
```{r}
# black RGB code 0 0 0
# red RGB code 255 0 0

result2=result %>%mutate(x1=if_else(cluster==3,0,x1) 
                          ,x2=if_else(cluster==3,0,x2) 
                          ,x3=if_else(cluster==3,0,x3) 
                          )%>%mutate(x1=if_else(cluster==1,255,x1) 
                          ,x2=if_else(cluster==1,0,x2) 
                          ,x3=if_else(cluster==1,0,x3)) %>% select(-cluster)
```

# convert 2 D back to 3 D
```{r}
result2arrary=array(unlist(result2),c(dim(image_array_old)[1],dim(image_array_old)[2],3))
```


```{r}
dim(result2arrary)
```


```{r}
magick::image_read(result2arrary/ 255)
```


# reference:

https://www.r-bloggers.com/2014/09/r-k-means-clustering-on-an-image/#google_vignette