---
title: "Principal component analysis "
subtitle: "with Mall Customers Datase"
execute:
  warning: false
  error: false
format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
---


Principal component analysis (PCA) is a method of reducing the dimensionality of data and is used to improve data visualization and speed up machine learning model training.






# load package




# data

## download data

https://www.kaggle.com/datasets/shwetabh123/mall-customer




## input data




## STANDARDIZE THE DATA


PCA is affected by scale, so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the data set’s features onto unit scale (mean = 0 and variance = 1), which is a requirement for the optimal performance of many machine learning algorithms. If you don’t scale your data, it can have a negative effect on your algorithm. 



## Before STANDARDIZE


## After STANDARDIZE



## inverse STANDARDIZE.for testing purpose only, have no impact on PCA.

for testing purpose only.



# PCA PROJECTION TO 2D





# reference:

https://www.youtube.com/watch?v=kApPBm1YsqU

https://builtin.com/machine-learning/pca-in-python

