---
title: "Financial data"
subtitle: "with quantmod"

author: "Tony Duan"

execute:
  warning: false
  error: false

format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-copy: true
---


```{r}
library(quantmod)
library(tidyverse)
library(yahoofinancer)
library(Quandl)
library(plotly)
library(finreportr)
library(rvest)
```

# stock price

```{r}
nifty_50 <- Index$new('^NSEI')

data001=nifty_50$get_history(start = '2023-01-01', interval = '1d') %>% unnest(cols = adj_close)

a=head(data001$adj_close,1)[[1]]

data001b=data001 %>% mutate(adj_close2=adj_close/a)

```

```{r}
length(unlist(data001$adj_close))
length(data001$adj_close)
```


```{r}
test=data001$adj_close %>% unlist()
```

```{r}
aapl <- Ticker$new('aapl')

data002=aapl$get_history(start = '2023-01-01', interval = '1d') %>% mutate(adj_close=adj_close %>% as.numeric())

a=head(data002$adj_close,1)[[1]]

data002b=data002 %>% mutate(adj_close2=adj_close/a)

```


```{r}
# initialize plot
fig <- plot_ly()

# add data from first dataframe Df1
fig <- fig %>%
    add_lines(data=data001b, name="NSEI50", x = ~date, y = ~adj_close2)

# add data from second dataframe Df2
fig <- fig %>%
    add_lines(data=data002b, name="apple", x = ~date, y = ~adj_close2)
# show figure
fig
```


# financials income statement

```{r}
library(chromote)
library(httr)
```

```{r}
url='https://finance.yahoo.com/quote/AMAT/financials'
```



```{r}
b <- ChromoteSession$new()
```



```{r}
# In a web browser, open a viewer for the headless browser. Works best with
# Chromium-based browsers.
#b$view()
b$Page$navigate(url)
```
```{r}
x <- b$DOM$getDocument()
```

```{r}
b$screenshot("sidebar.png")
```

```{r}
page=b$Runtime$evaluate("document.querySelector('html').outerHTML")$result$value %>% 
  read_html()
```


```{r}
b$close()
```

```{r}
col1=page%>% 
  html_elements(".row .column:nth-child(1)") %>% html_text2()  %>% head(33)

```



```{r}
col2=page%>% 
  html_elements(".row .column:nth-child(2)") %>% html_text2()
```

```{r}
col3=page%>% 
  html_elements(".row .column:nth-child(3)") %>% html_text2()

```

```{r}
col4=page%>% 
  html_elements(".row .column:nth-child(4)") %>% html_text2()

```

```{r}
col5=page%>% 
  html_elements(".row .column:nth-child(5)") %>% html_text2()

```


```{r}
col6=page%>% 
  html_elements(".row .column:nth-child(6)") %>% html_text2()

```


```{r}
data001=data.frame(col1,col2,col3,col4,col5,col6)
```

```{r}
library(janitor )
colnames(data001) <- data001[1,]
data001 <- data001[-1, ]  %>%clean_names()
```

```{r}
glimpse(data001)
```


```{r}
data002=data001 %>% mutate(breakdown=breakdown %>% str_remove_all('HTML_TAG_START HTML_TAG_END')
                           ,ttm=round(as.numeric(gsub(",","",ttm)))
                           ,year_2024=round(as.numeric(gsub(",","",x10_31_2024)))
                             ,year_2022=round(as.numeric(gsub(",","",x10_31_2022)))
                             ,year_2021=round(as.numeric(gsub(",","",x10_31_2021)))
                             ,year_2023=round(as.numeric(gsub(",","",x10_31_2023)))
                           ) %>% select(-x10_31_2023,-x10_31_2022,-x10_31_2021,-x10_31_2024)
```


```{r}
glimpse(data002)
```


```{r}
options(scipen = 999)

library(knitr)
kable(data002)
```



# resource:

https://github.com/rsquaredacademy/yahoofinancer

https://github.com/sewardlee337/finreportr

https://www.youtube.com/watch?v=uVHGgSXtQmE

