---
title: "chromote"
author: "Tony Duan"

execute:
  warning: false
  error: false
  eval: false

format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
---

```{r}
library(tidyverse)
library(chromote)
```

```{r}
packageVersion("chromote")
```


# create view
```{r}
library(chromote)

b <- ChromoteSession$new()

# In a web browser, open a viewer for the headless browser. Works best with
# Chromium-based browsers.
b$view()
```

```{r}
b$Browser$getVersion()
```

# go to page
```{r}
b$Page$navigate("https://www.r-project.org/")
```
# take picture
```{r}
# Saves to screenshot.png
b$screenshot()
```

```{r}
# Takes a screenshot of elements picked out by CSS selector
is_interactive <- interactive() # Display screenshot if interactive
b$screenshot("sidebar.png", selector = "h1" ,show = is_interactive)
```


# take picture as pdf
```{r}
b$screenshot_pdf(filename='page.pdf')
```

# Reference:

https://rstudio.github.io/chromote/

