---
title: "All page first time"
subtitle: "with whiskyfun.com data"
author: "Tony Duan"

execute:
  warning: false
  error: false
  eval: false
format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
---


```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(openxlsx)
library(readxl)
```

```{r}
packageVersion("rvest")
```


# all review page

# first page
```{r}
first_url='https://www.whiskyfun.com'
first_page=read_html(first_url)
```


```{r}
last_page <- first_page %>%
  html_elements(css = "a.textegrandfoncegras")%>% html_attr("href")
```


# start from secound page


```{r}
page_list=c()
```


```{r}
url='https://www.whiskyfun.com/archivemarch24-2-Port-Ellen-Glen-Grant.html'

page=read_html(first_url)

last_page <- (first_page %>%html_elements(css = "font:nth-child(1) strong a")%>%html_attr("href"))[1]

print(last_page)
page_list=c(page_list,last_page)
```

# start to download 1000 pages

```{r}
last_page='https://www.whiskyfun.com/archivemarch24-2-Port-Ellen-Glen-Grant.html'

page_list=c()
data_list=tibble()

i=0
a=0

while (i < 1000) {
  loop_num=i
  print(paste0("current page: ",loop_num))
  old_page=last_page
  tryCatch({
    page=read_html(last_page)
    i=i+1
    
  Sys.sleep(runif(n=1, min=0.1, max=0.3))
 },error = function(msg){print('eeeeeeeeeeeeeeeeeeeeeeeeeeeee')
    i=i-1
    print(paste0("new i : ",i))
    a=a+1
    })
   if(a>10){break}
  

 last_page <- (page %>%html_elements(css = "font:nth-child(1) strong a")%>%html_attr("href"))[1]
  last_page=paste0('https://www.whiskyfun.com/',last_page)
    
  page_link_count=str_count(last_page,'www.whiskyfun.com')
  last_page=ifelse(page_link_count==2,str_replace(last_page,"https://www.whiskyfun.com/",""),last_page)
  
  last_page=last_page
  print(last_page)
  page_list=c(page_list,last_page)
  
  #######################
  review_html_elements=".textegrandfoncegras , .TextenormalNEW, .Textenormal,td > font,div td font"
  bottle_review=page  %>% html_elements(review_html_elements) %>% html_text2()
# remove space element

  bottle_review1=bottle_review[bottle_review %>% str_detect(' points')]

  bottle_review2=bottle_review1[bottle_review1 %>% str_detect('Nose:')]

  bottle_review2=bottle_review2%>% str_replace("Palate:", "Mouth")%>% str_replace("–", "-")

  bottle_name=str_extract(bottle_review2, regex( "[^)]+"))
  bottle_name=paste0(bottle_name,")")
  print(head(bottle_name,2))
  print(paste0("this page have bottle: ",length(bottle_name)))
  

  ##### break the loop if can not download continue >=3 pages
  if (length(bottle_name)==1){fail_num=fail_num+1}else{fail_num=0}
    
  if (fail_num>=3){
    print(paste0("breaking page url: ",old_page))
    break
    }
  ################################################################
  
  # res <- str_match(bottle_review2, " \\s*(.*?)\\s*points")
  # bottle_score=paste("SGP:",res[,2]," points")%>% str_replace("–", "-")
  # 
  # res <- str_match(bottle_score, " - \\s*(.*?)\\s*points")
  # bottle_final_score=res[,2]
  # 
  # res <- str_match(bottle_review2, "Nose:\\s*(.*?)\\s*Mouth")
  # bottle_name_nose=paste("Nose:",res[,2])
  # 
  # res <- str_match(bottle_review2, "Mouth\\s*(.*?)\\s*Finish:")
  # bottle_name_mouth=paste("Mouth:",res[,2])
  # 
  # res <- str_match(bottle_review2, "Colour\\s*(.*?)\\s*\\.")
  # bottle_name_colour=paste("Colour ",res[,2])
  # 
  # res <- str_match(bottle_review2, "Finish:\\s*(.*?)\\s*Comments:")
  # bottle_name_finish=paste("Finish:",res[,2])
  # 
  # res <- str_match(bottle_review2, "Comments:\\s*(.*?)\\s*SGP:")
  # bottle_name_comments=paste("Comments:",res[,2])
  # 
  # data=tibble(bottle_review2,bottle_name,bottle_name_nose,bottle_name_mouth,bottle_name_finish,bottle_name_colour,bottle_name_comments,bottle_score,bottle_final_score,old_page,loop_num) %>% unique()
  # 
  # data_list=rbind(data_list,data)
  # print(paste0("total bootle downlaoded: ",nrow(data_list)))
  data=tibble(bottle_review2,bottle_name) %>% unique()
  data_list=rbind(data_list,data)
  print(paste0("total bootle downlaoded: ",nrow(data_list)))
  

  ####### ouput every 10 page
  if (i%%10==0){

      print(paste0("output to excel: ", i))
      write.xlsx(data_list,'all_page_review_all.xlsx')
     }
  
  Sys.sleep(runif(n=1, min=0.1, max=0.5))
}

write.xlsx(data_list,'all_page_review_all.xlsx')
```














# after(https://www.whiskyfun.com/ArchiveSeptember04.html)  start to download 10 pages


```{r}
last_page='https://www.whiskyfun.com/ArchiveSeptember04.html'
fail_num=0
page_list=c()
data_list=tibble()

for (i in seq(1:100)){

  print(paste0("current page",i))
  old_page=last_page
  tryCatch({
    page=read_html(last_page)
    Sys.sleep(runif(n=1, min=0.1, max=0.5))
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
  
  Sys.sleep(runif(n=1, min=0.1, max=0.3))
  
  last_page <- (page %>%html_elements("font:nth-child(1) b a")%>%html_attr("href"))[1]
  last_page=paste0('https://www.whiskyfun.com/',last_page)
    
  page_link_count=str_count(last_page,'www.whiskyfun.com')
  last_page=ifelse(page_link_count==2,str_replace(last_page,"https://www.whiskyfun.com/",""),last_page)
  
  last_page=last_page
  print(last_page)
  page_list=c(page_list,last_page)
  
  #######################
  review_html_elements=".textegrandfoncegras , .TextenormalNEW, .Textenormal,td > font,div td font"
  bottle_review=page  %>% html_elements(review_html_elements) %>% html_text2()
# remove space element

  bottle_review1=bottle_review[bottle_review %>% str_detect(' points')]

  bottle_review2=bottle_review1[bottle_review1 %>% str_detect('Nose:')]

  bottle_review2=bottle_review2%>% str_replace("Palate:", "Mouth")%>% str_replace("–", "-")

  bottle_name=str_extract(bottle_review2, regex( "[^)]+"))
  bottle_name=paste0(bottle_name,")")
  print(head(bottle_name,1))
  print(paste0("this page have bottle: ",length(bottle_name)))
  

  ##### break the loop if can not download continue >=3 pages
  if (length(bottle_name)==1){fail_num=fail_num+1}else{fail_num=0}
    
  if (fail_num>=3){
    print(paste0("breaking page url: ",old_page))
    break
    }
  ################################################################
  
  res <- str_match(bottle_review2, " \\s*(.*?)\\s*points")
  bottle_score=paste("SGP:",res[,2]," points")%>% str_replace("–", "-")

  res <- str_match(bottle_score, " - \\s*(.*?)\\s*points")
  bottle_final_score=res[,2]

  res <- str_match(bottle_review2, "Nose:\\s*(.*?)\\s*Mouth")
  bottle_name_nose=paste("Nose:",res[,2])

  res <- str_match(bottle_review2, "Mouth\\s*(.*?)\\s*Finish:")
  bottle_name_mouth=paste("Mouth:",res[,2])

  res <- str_match(bottle_review2, "Colour\\s*(.*?)\\s*\\.")
  bottle_name_colour=paste("Colour ",res[,2])

  res <- str_match(bottle_review2, "Finish:\\s*(.*?)\\s*Comments:")
  bottle_name_finish=paste("Finish:",res[,2])

  res <- str_match(bottle_review2, "Comments:\\s*(.*?)\\s*SGP:")
  bottle_name_comments=paste("Comments:",res[,2])

  data=tibble(bottle_review2,bottle_name,bottle_name_nose,bottle_name_mouth,bottle_name_finish,bottle_name_colour,bottle_name_comments,bottle_score,bottle_final_score,old_page) %>% unique()

  data_list=rbind(data_list,data)
  # ouput every 10 page
  if (i%%10==0){
      print(paste0("output to excel: ", i/10))
      write.xlsx(data_list,'all_page_review_v2.xlsx')
     }
  
  Sys.sleep(runif(n=1, min=0.1, max=0.5))
}

write.xlsx(data_list,'all_page_review_missing.xlsx')
```

# download missing pages with speical method


```{r}
missing_page=c('https://www.whiskyfun.com/archiveaugust22-2-Speyburn-Caroni.html'
               ,'https://www.whiskyfun.com/archivejuly22-2-Strathisla-Dufftown.html')
```


# ouput

```{r}
write.xlsx(data_list,'all_page_review.xlsx')
#write.xlsx(page_list_data,'all_page_link.xlsx')
```


# whiskyfun first page
https://www.whiskyfun.com/ArchiveJan04.html

# whiskyfun last muic page
https://www.whiskyfun.com/archivejanuary18-1-Linkwood-Ardmore-Clynelish.html




