---
title: "China accident map"
subtitle: "with mapview"
author: "Tony Duan"

execute:
  warning: false
  error: false

format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-copy: true
---

# data

data source :https://github.com/percent4/chinese_incident_tracker


```{r}
library(tidyverse)
library(rvest)
library(jsonlite)
library(curl)
library(lubridate)
library(plotly)
library(ggplot2)
library(openxlsx)
library(readxl)
```
# one file 


```{r}
#url <- "https://raw.githubusercontent.com/percent4/chinese_incident_tracker/main/elk/data/00105670-df53-4be8-9039-8a07fe2d2b4d.json"
#download.file(url,"./data/SAFI.json", mode = "wb")
```

```{r}
data001 <- read_json("./data/SAFI.json")
```


```{r}
data002=data001 %>% as.data.frame()
colnames(data002)[14] = "latitude"
colnames(data002)[15] = "longitude"
glimpse(data002)
```

# all file

```{r}
#url="https://github.com/percent4/chinese_incident_tracker/archive/refs/heads/main.zip"
#download.file(url,"./data/data.zip", mode = "wb")

```

```{r}
#unzip("./data/data.zip",exdir="./data/out")
```

```{r}
from <- "./data/out/chinese_incident_tracker-main/elk/data"
to   <- "./data/json_folder"
file.copy(list.files(from, full.names = TRUE), 
          to, 
          recursive = TRUE)
```


```{r}
#list.files("./data/json_folder")
```


```{r}
all_data=tibble()

for (i in list.files("./data/json_folder")) {
  #print(i)
  data001=read_json(paste0("./data/json_folder/",i))
  data002=data001 %>% as.data.frame()
  colnames(data002)[14] = "Longitude"
  colnames(data002)[15] = "Latitude"
  #print(data002)
  
  all_data=rbind(all_data,data002)
}
```


```{r}
all_data=all_data %>% mutate(text=paste0(incident_type," ","死亡人数:",person_death_num," 受伤人数:",person_injury_num)
                             ,month_year= format_ISO8601(ymd(start_date), precision = "ym")
                             )
```

```{r}
glimpse(all_data)
```


```{r}
#write.xlsx(all_data,'all_data.xlsx')
```

# chart

group to month
```{r}
chartdata001=all_data %>% group_by(month_year)  %>%  summarise(person_death_num=sum(person_death_num)
                                                           ,person_injury_num=sum(person_injury_num)
                                                           )

```

wide to long
```{r}
chartdata002=chartdata001 %>%select(month_year,person_death_num,person_injury_num) %>% 
  pivot_longer(!c(month_year), names_to = 'type', values_to = 'DATA')

```

```{r}
gg=ggplot(chartdata001, aes(x=month_year, y=person_death_num,label = person_death_num))+
  geom_bar(stat="identity",fill='red')+ geom_text(vjust = -1,
              position = position_dodge(width = 0.9))+ theme_bw()


ggplotly(gg)
```


```{r}
gg=ggplot(chartdata002, aes(fill=type, y=DATA, x=month_year)) +
    geom_col(position = "dodge") +
    geom_text(aes(label = DATA), vjust = 1.5,
              position = position_dodge(width = 0.9))+scale_y_log10()+ theme_light()

pp=ggplotly(gg)

pp
```



# map

```{r}
all_data2 =all_data %>%  mutate(report=report %>% str_trunc(100))
```

```{r}
#write.xlsx(all_data2,'all_data2.xlsx')
```

```{r fig.height=8}
library(mapview)
library(sf)
library(stringr)

mapview(all_data2, map.types='OpenStreetMap',label='text',xcol = "Longitude", ycol = "Latitude", zcol='incident_type',cex="person_death_num",crs = 4269, grid = FALSE)
```




# resouce:


https://github.com/percent4/chinese_incident_tracker

https://github.com/r-spatial/mapview

https://maps.clb.org.hk/


