---
title: "on bottle review with log in"
subtitle: "with whiskybase.com data"
author: "Tony Duan"

execute:
  warning: false
  error: false
  eval: false
  
format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
---


```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(openxlsx)
library(readxl)
library(httr)
```

# check connection

```{r}
url='https://www.google.com.hk/'

wb_url='https://www.whiskybase.com/'
```


```{r}
my_session <- session(url)
```

200 is good
```{r}
my_session$response$status_code
```

# adding agent

some website need agent header

```{r}
user_a <- user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36")

session_with_ua <- session(wb_url, user_a)
```


```{r}
session_with_ua$response$status_code
```

show agent header

```{r}
session_with_ua$response$request$options$useragent
```

# go to page when log in
```{r}
session_with_ua <- session_with_ua |> 
  session_jump_to("https://www.whiskybase.com/whiskies")
session_with_ua
```
# check session visit history
```{r}
session_with_ua %>% session_history()
```



# log in 


## find require info

form 4 is login form

```{r}
read_html('https://www.whiskybase.com/') %>%  html_form("form")
```

# submit account and password

```{r}
pgform <- html_form(session_with_ua)[[4]]
pgform <- set_values(pgform,username = "Jcwinningco@163.com", password = "qwe123WB")
```

```{r}
result <- submit_form(session_with_ua, pgform)
```


```{r}
session_with_ua <- result |> 
  session_jump_to('https://www.whiskybase.com/whiskies/whisky/147142/macallan-12-year-old')

session_with_ua
```
# check login names

```{r}
review_people=page%>% html_nodes('.wb--username')%>% html_text()
review_people
```

# save html page
```{r}
page=read_html(session_with_ua)
```

```{r}
text=page%>% html_nodes("*")%>% html_text2()
```


```{r}
write_delim(tibble(text), "./data/one bottle with log in.txt")
```


# check score people

```{r}
session_with_ua <- session_with_ua |> 
  session_jump_to('https://www.whiskybase.com/whiskies/whisky/147142/macallan-12-year-old#whisky-community')
```


```{r}
session_with_ua %>% session_history()
```
```{r}
page=read_html(session_with_ua)
```

## in whisky list
```{r}
review_people=page%>% html_nodes('#whisky-community a')%>% html_text2()
review_people
```





