---
title: "All bottle from a distillery review"
subtitle: "with whiskybase.com data"
author: "Tony Duan"

execute:
  warning: false
  error: false
  eval: false
format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
---


```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(openxlsx)
library(readxl)
library(janitor)
library(writexl)
```


```{r}
url='https://www.whiskybase.com/whiskies/distillery/257/kawasaki'
page=read_html(url)
element=page %>% 
  html_nodes("*") %>% 
  html_attr("class") %>% 
  unique()
```


```{r}
data=page%>% html_nodes("table")%>%html_table(fill = TRUE) %>% as.data.frame() %>% clean_names()
```

```{r}
bottle_link= page%>%html_nodes(".clickable")%>% html_attr('href')
```

```{r}
names(data)
```


```{r}
data2=data %>% mutate(var_2=str_trim(var_2),l=ifelse(var_2=='',1,0)) %>% filter(l==1) %>% mutate(bottle_link=bottle_link) %>% select(name,stated_age,strength,bottled,casknumber,rating,bottle_link)
```

output

```{r}
write.xlsx(data2,'./output/all bottler under one distillery.xlsx')
```


# add detail

```{r}
data002=read_excel('./output/all bottler under one distillery.xlsx')
```



```{r}
rating_people_num_list=c()
avg_price_list=c()
lowest_price_list=c()
cask_type_list=c() 
pic_link_list=c()
wb_id=c()
start_time=now()
cask_number_list=c()
number_of_bottle_list=c()
score_list=c()
bottler_list=c()
bottle_list=c()
strength_list=c()
bottle_link_list=c()
order_num=0
```



```{r}


for (i in data002$bottle_link){
    Sys.sleep(runif(n=1, min=0.1, max=0.5))
    order_num=order_num+1
    tryCatch({
    
    print(paste('#############',order_num,'bottle ######################################## '))
    print(i)
    url=i
    page = read_html(url)
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
    #################### bottle_link_list
    
    bottle_link_list=c(bottle_link_list,i)
      
    ###################### score
    bottle=(page%>% html_nodes('h1')%>% html_text())[1]
    bottle=bottle %>% str_remove_all('\n') %>% str_remove_all('\t')
    print(paste0("bottle: ",(bottle)[1]))
    bottle_list=c(bottle_list,bottle)
    
    
    ###################### score
    score=(page%>% html_nodes('.votes-rating-current')%>% html_text())[1]
    print(paste0("score: ",score))
    score_list=c(score_list,score)
    
    ####################### rating_people_num
    rating_people_num=page%>% html_nodes('.votes-count')%>% html_text()
    print(rating_people_num)[1]
    rating_people_num_list=c(rating_people_num_list,rating_people_num[1])
    
    
    ##################### lowest price
    lowest_price=page%>% html_nodes('.wb--shop-links-panel--price')%>% html_text()
    lowest_price2=if(identical(lowest_price, character(0))==TRUE){0}else{lowest_price}
    print(lowest_price2)
    lowest_price_list=c(lowest_price_list,lowest_price2)
    
    ############################# average price
    avg_price=page%>% html_nodes('p+ p')%>% html_text()
    avg_price6=case_when(str_detect(avg_price, "[0-9]")==TRUE~avg_price,.default='')
    print(paste('price is :',avg_price6[1]))
    avg_price_list=c(avg_price_list,avg_price6[1])
    
    ################################## cask type
    bottle_name=page%>% html_nodes('#whisky-details dt')%>% html_text()
    bottle_value=page%>% html_nodes('#whisky-details dt+ dd')%>% html_text()
    bottle_name_value=data.frame(bottle_name,bottle_value)
    cask=bottle_name_value%>% filter(bottle_name=='Cask Type') %>% select(bottle_value)
    cask2=if(nrow(cask)==0){'unknow cask'}else{ unname(unlist(cask[1,]))}
    print(cask2)
    cask_type_list=c(cask_type_list,cask2)
    
    ################################## Bottler
    #bottle_name=page%>% html_nodes('#whisky-details dt')%>% html_text()
    #bottle_value=page%>% html_nodes('#whisky-details dt+ dd')%>% html_text()
    #bottle_name_value=data.frame(bottle_name,bottle_value)
    bottler=bottle_name_value%>% filter(bottle_name=='Bottler') %>% select(bottle_value)
    bottler=if(nrow(bottler)==0){'unknow Bottler'}else{ unname(unlist(bottler[1,]))}
    print(bottler)
    bottler_list=c(bottler_list,bottler)
    
    ################################## strength
    #bottle_name=page%>% html_nodes('#whisky-details dt')%>% html_text()
    #bottle_value=page%>% html_nodes('#whisky-details dt+ dd')%>% html_text()
    #bottle_name_value=data.frame(bottle_name,bottle_value)
    strength=bottle_name_value%>% filter(bottle_name=='Strength') %>% select(bottle_value)
    strength=if(nrow(strength)==0){'unknow strength'}else{ unname(unlist(strength[1,]))}
    print(strength)
    strength_list=c(strength_list,strength)
    
    
      
    ##################### number_of_bottle 
    number_of_bottle1=bottle_name_value%>% filter(bottle_name=='Number of bottles') %>% select(bottle_value)
    number_of_bottle2=if(nrow(number_of_bottle1)==0){'unknow Number of bottles'}else{ unname(unlist(number_of_bottle1[1,]))}
      
    print(number_of_bottle2)
    number_of_bottle_list=c(number_of_bottle_list,number_of_bottle2)
      
    ##################### Casknumber 
    cask_number1=bottle_name_value%>% filter(bottle_name=='Casknumber') %>% select(bottle_value)
    cask_number2=if(nrow(cask_number1)==0){'unknow Casknumber'}else{ unname(unlist(cask_number1[1,]))}
      
    print(paste('casknumber:',cask_number2))
    cask_number_list=c(cask_number_list,cask_number2)
      
      
    ########################################### wb id 
    id_name=page%>% html_nodes(' #whisky-details dd:nth-child(2)')%>% html_text()
    print(id_name)
    wb_id=c(wb_id,id_name)
      
    ####### check 
      
    id_num=as.numeric(str_replace(id_name,'WB',''))
    print(id_num)
      
    a=(str_split(url,'/')[[1]])
    b=as.numeric(a[length(a)-1])
    #print(paste("wb id from link",b))
    #print(paste("wb id from page",id_num))
    if(id_num!=b){
        print(i)
        print('############## error !!!!!!!!##################')
        break
    }
    ##################     pic link   #######################
    pic_link=(page%>% html_nodes('.photo')%>% html_attr('href'))[1]
    pic_link2=if(identical(pic_link, character(0))==TRUE){0}else{pic_link}
      
    print(pic_link2)
    pic_link_list=c(pic_link_list,pic_link2)
    
 ######### output to excel on every 10 bottle
  if(order_num%%10==0){
    data003=cbind((data002[1:order_num,]),bottle_list,score_list,rating_people_num_list,lowest_price_list,avg_price_list,cask_type_list,number_of_bottle_list,bottler_list,strength_list,cask_number_list,wb_id,pic_link_list,bottle_link_list)%>% as_tibble()
    
    
    write_xlsx(data003,'./output/all bottel under one distillery with detail.xlsx')
  }
}
#########################################################  

```


```{r}
data003=cbind(data002,bottle_list,score_list,rating_people_num_list,lowest_price_list,avg_price_list,cask_type_list,number_of_bottle_list,bottler_list,strength_list,cask_number_list,wb_id,pic_link_list,bottle_link_list) %>% as_tibble()

write_xlsx(data003,'./output/all bottel under one distillery with detail.xlsx')
```