---
title: "China accident map"
author: "Tony Duan"

execute:
  warning: false
  error: false

format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-copy: true
---

# data

data source :https://github.com/percent4/chinese_incident_tracker


```{r}
library(tidyverse)
library(rvest)
library(jsonlite)
library(curl)
```
# one file 


```{r}
#url <- "https://raw.githubusercontent.com/percent4/chinese_incident_tracker/main/elk/data/00105670-df53-4be8-9039-8a07fe2d2b4d.json"
#download.file(url,"./data/SAFI.json", mode = "wb")
```

```{r}
data001 <- read_json("./data/SAFI.json")
```


```{r}
data002=data001 %>% as.data.frame()
colnames(data002)[14] = "latitude"
colnames(data002)[15] = "longitude"
glimpse(data002)
```

# all file

```{r}
#url="https://github.com/percent4/chinese_incident_tracker/archive/refs/heads/main.zip"
#download.file(url,"./data/data.zip", mode = "wb")

```

```{r}
#unzip("./data/data.zip",exdir="./data/out")
```

```{r}
from <- "./data/out/chinese_incident_tracker-main/elk/data"
to   <- "./data/json_folder"
file.copy(list.files(from, full.names = TRUE), 
          to, 
          recursive = TRUE)
```


```{r}
#list.files("./data/json_folder")
```


```{r}
all_data=tibble()

for (i in list.files("./data/json_folder")) {
  #print(i)
  data001=read_json(paste0("./data/json_folder/",i))
  data002=data001 %>% as.data.frame()
  colnames(data002)[14] = "Longitude"
  colnames(data002)[15] = "Latitude"
  #print(data002)
  
  all_data=rbind(all_data,data002)
}
```

```{r}
glimpse(all_data)
```


```{r fig.height=12}
library(mapview)
library(sf)

mapview(all_data, map.types='OpenStreetMap',zoom=5,label='incident_type',xcol = "Longitude", ycol = "Latitude", crs = 4269, grid = FALSE)
```




# resouce:


https://github.com/percent4/chinese_incident_tracker

https://github.com/r-spatial/mapview


